### ISSUE TITLE
c2eo crashes with segfault

### ISSUE THREAD

**Issue by kniazkov** [polystat/c2eo#47]
I built project as described. Then I created the .c source file that contains:
```
void main(void) {

}
```
I saved it as `test.c` and then tried to execute `launcher.py`:
```
ivan@test:~/c2eo/project/bin$ python3 launcher.py test.c 
argc = 2
argv = ['launcher.py', 'test.c']
Launcher Directory is: /home/ivan/c2eo/project/bin/launcher.py
Directory /home/ivan/c2eo/result/eo/c2eo/src contain: []
Directory /home/ivan/c2eo/project/assembly contain: []
c2eoProgram = /home/ivan/c2eo/project/bin/c2eo /home/ivan/c2eo/project/bin/test.c static01
Name of Function: main
  Func Kind Name: Function
  It's definition
  Has Body
  Does not have Trivial Body
  Body pointer != 0
  Function is defined
  Function is global
  Function returns value
  Function has 0 parameters
  Returns integer type
  Function isn't Inline
  It is CompoundStmt statement. stmtClass = 8
Segmentation fault (core dumped)
Hello from collector!!!!
Current Working Directory is: /home/ivan/c2eo/project/bin
Resul Directory is: /home/ivan/c2eo/project/bin/../assembly/
Static objects. Directory /home/ivan/c2eo/project/bin/../assembly/ contain files: []
Global objects. Directory /home/ivan/c2eo/project/bin/../assembly/ contain files: []
+package c2eo.src
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

+alias c2eo.ctypes.c_bool
+alias c2eo.ctypes.c_char
+alias c2eo.ctypes.c_float64
+alias c2eo.ctypes.c_int16
+alias c2eo.ctypes.c_int32
+alias c2eo.ctypes.c_int64

[arg] > global


Launcher: OK!

```
No output data was created. I noted there `Segmentation fault (core dumped)` in the log.
I started `c2eo` separately and got the following result:
```
ivan@test:~/c2eo/project/bin$ ./c2eo test.c xxx
/home/ivan/c2eo/project/bin/test.c:1:1: warning: return type of 'main' is not 'int' [-Wmain-return-type]
void main(void) {
^
/home/ivan/c2eo/project/bin/test.c:1:1: note: change return type to 'int'
void main(void) {
^~~~
int
Name of Function: main
  Func Kind Name: Function
  It's definition
  Has Body
  Has Trivial Body
  Body pointer != 0
  Function is defined
  Function is global
  Function returns value
  Function has 0 parameters
  Returns other type
  Function isn't Inline
  It is CompoundStmt statement. stmtClass = 8
1 warning generated.
Segmentation fault (core dumped)
```

So, segfault again. I started the program with gdb and got the backtrace:
```
ivan@test:~/c2eo/project/bin$ gdb --args ./c2eo test.c xxx
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./c2eo...
(No debugging symbols found in ./c2eo)
(gdb) r
Starting program: /home/ivan/c2eo/project/bin/c2eo test.c xxx
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
/home/ivan/c2eo/project/bin/test.c:1:1: warning: return type of 'main' is not 'int' [-Wmain-return-type]
void main(void) {
^
/home/ivan/c2eo/project/bin/test.c:1:1: note: change return type to 'int'
void main(void) {
^~~~
int
Name of Function: main
  Func Kind Name: Function
  It's definition
  Has Body
  Has Trivial Body
  Body pointer != 0
  Function is defined
  Function is global
  Function returns value
  Function has 0 parameters
  Returns other type
  Function isn't Inline
  It is CompoundStmt statement. stmtClass = 8
1 warning generated.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4a9ac08 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff4a9ac08 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00005555555d9095 in CompoundStmtGen::Generate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#2  0x00005555555d895e in GlobalFuncGen::Generate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#3  0x00005555555d8b1a in SpaceGen::Generate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#4  0x000055555558e4e2 in generateSpace(SpaceGen&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#5  0x000055555558e05b in main ()
```

**Comment by kreofil** [comment]
Проблема решена
